os: linux
dist: focal

language: java
jdk: oraclejdk11

before_script:
  - git clone https://github.com/lzaoral/collaborative-rsa-demo
  - cd collaborative-rsa-demo
  - cmake .
  - make
  - cp smpc_rsa ../applet/src/test/java/tests/
  - cd ..

script:
  - ./gradlew check
  - ./gradlew buildJavaCard --info
